<?php

/*
 * Editor server script for DB table user
 * Automatically generated by http://editor.datatables.net/generator
 */

// DataTables PHP library
include( "lib/DataTables.php" );

// Alias Editor classes so they are easy to use
use
	DataTables\Editor,
	DataTables\Editor\Field,
	DataTables\Editor\Format,
	DataTables\Editor\Join,
	DataTables\Editor\Validate;


// Build our Editor instance and process the data coming from _POST
Editor::inst( $db, 'artikli', 'id' )
	->fields(
			
		Field::inst( 'artikli.id' ),
			
		Field::inst( 'artikli.tip' )
			->validator( 'Validate::numeric' ),
			
		Field::inst( 'artikli.marka' )
			->validator( 'Validate::numeric' ),
			
		Field::inst( 'tipovi.naziv' ),

		Field::inst( 'marke.naziv' ),

		Field::inst( 'artikli.naziv' )
			->validator( 'Validate::notEmpty' ),

		Field::inst( 'artikli.opis' )
			->validator( 'Validate::notEmpty' ),

		Field::inst( 'artikli.cena' )
			->validator( 'Validate::numeric' ),

		Field::inst( 'artikli.stanje' )
			->validator( 'Validate::numeric' )
	)
	->leftJoin( 'tipovi', 'artikli.tip', '=', 'tipovi.id' )
	->leftJoin( 'marke', 'artikli.marka', '=', 'marke.id' )
	->process( $_POST )
	->json();

