<?php

/*
 * Editor server script for DB table user
 * Automatically generated by http://editor.datatables.net/generator
 */

// DataTables PHP library
include( "lib/DataTables.php" );

// Alias Editor classes so they are easy to use
use
	DataTables\Editor,
	DataTables\Editor\Field,
	DataTables\Editor\Format,
	DataTables\Editor\Join,
	DataTables\Editor\Validate;


// Build our Editor instance and process the data coming from _POST
Editor::inst( $db, 'kuponi', 'id' )
	->fields(
		Field::inst( 'artikl' )
			->validator( 'Validate::numeric' ),

		Field::inst( 'ime' )
			->validator( 'Validate::notEmpty' ),

		Field::inst( 'email' )
			->validator( 'Validate::email' ),

		Field::inst( 'adresa' )
			->validator( 'Validate::notEmpty' ),
			
		Field::inst( 'telefon' )
			->validator( 'Validate::numeric' )
	)
	->process( $_POST )
	->json();

