
/*
 * Editor client script for DB table kuponi
 * Automatically generated by http://editor.datatables.net/generator
 */

(function($){

	/* Formatting function for row details - modify as you need */
	function format ( data ) {

		var artikl = 'Uklonjen iz baze... :/';

		for (var i = 0; i < artikli.length; i++) {
			if (artikli[i].id == data.artikl) 
				artikl = artikli[i];
		};

	    // `d` is the original data object for the row
	    return '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;">'+
	        '<tr>'+
	            '<td>Dodatne informacije:</td>'+
	            '<td>Kupio je artikl: '+artikl.naziv+' '+artikl.opis+'</td>'+
	        '</tr>'+
	    '</table>';
	}

	$(document).ready(function() {

		var editor = new $.fn.dataTable.Editor( {
			"ajax": "php/table.kuponi.php",
			"table": "#kuponi",
			"fields": [
				{
					"label": "Ime",
					"name": "ime",
					"type": "text"
				},
				{
					"label": "Email",
					"name": "email",
					"type": "text"
				},
				{
					"label": "Adresa",
					"name": "adresa",
					"type": "textarea"
				},
				{
					"label": "Telefon",
					"name": "telefon",
					"type": "text"
				}
			]
		} );
	 
	    // Activate the bubble editor on click of a table cell
	    $('#kuponi').on( 'click', 'tbody td:not(:first-child)', 
	    	function (e) {
		        editor.inline( this );
	    } );

		var table = $('#kuponi').DataTable( {
			dom: "Tfrtip",
			ajax: "php/table.kuponi.php",
			language: {
	            "url": "http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Serbian.json"
	        },
			columns: [
	            {
	                "className":      'details-control',
	                "orderable":      false,
	                "data":           null,
	                "defaultContent": ''
	            },
				{
					"data": "artikl"
				},
				{
					"data": "ime"
				},
				{
					"data": "adresa"
				},
				{
					"data": "email"
				},
				{
					"data": "telefon"
				}
			],
	        order: [ 1, 'asc' ],
			tableTools: {
				sRowSelect: "os",
	            sRowSelector: 'td:first-child',
			    sSwfPath: "http://cdn.datatables.net/tabletools/2.2.3/swf/copy_csv_xls_pdf.swf",

				aButtons: [
					{ "sExtends": "editor_edit", 
			            sButtonText: "Izmeni",  
						"editor": editor 
					},

					{ "sExtends": "editor_remove", 
			            sButtonText: "Obrisi", 
						"editor": editor 
					},

			        {
			            sExtends: "collection",
			            sButtonText: "Sacuvaj",
			            sButtonClass: "save-collection",
			            aButtons: [ 'copy', 'csv', 'xls', 'pdf' ]
			        }
				]
			}
		} );

		// Add event listener for opening and closing details
	    $('#kuponi tbody').on('click', 'td.details-control', 
	    	function () {
		        var tr = $(this).closest('tr');
		        console.log(table);
		        var row = table.row( tr );
		 
		        if ( row.child.isShown() ) {
		            // This row is already open - close it
		            row.child.hide();
		            tr.removeClass('shown');
		        }
		        else {
		            // Open this row
		            row.child( format(row.data()) ).show();
		            tr.addClass('shown');
	        }
	    } );
	} );

}(jQuery));

