
/*
 * Editor client script for DB table marke
 * Automatically generated by http://editor.datatables.net/generator
 */

(function($){

$(document).ready(function() {
	var editor = new $.fn.dataTable.Editor( {
		"ajax": "php/table.marke.php",
		"table": "#marke",
		"fields": [
			{
				"label": "Naziv",
				"name": "naziv",
				"type": "text"
			},
			{
				"label": "Opis",
				"name": "opis",
				"type": "textarea"
			}
		]
	} );
 
    // Activate the bubble editor on click of a table cell
    $('#marke').on( 'click', 'tbody td:not(:first-child)', 
    	function (e) {
    		if ( $(this).index() > 0 ) {
	            editor.inline( this );
	        }
    } );

	$('#marke').dataTable( {
		dom: "Tfrtip",
		ajax: "php/table.marke.php",
		language: {
            "url": "http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Serbian.json"
        },
		columns: [
			{
				"data": "id"
			},
			{
				"data": "naziv"
			},
			{
				"data": "opis"
			}
		],
        order: [ 1, 'asc' ],
		tableTools: {
			sRowSelect: "os",
            sRowSelector: 'td:first-child',
		    sSwfPath: "http://cdn.datatables.net/tabletools/2.2.3/swf/copy_csv_xls_pdf.swf",

			aButtons: [
				{ "sExtends": "editor_create", 
		            sButtonText: "Kreiraj",  
					"editor": editor 
				},

				{ "sExtends": "editor_edit", 
		            sButtonText: "Izmeni",  
					"editor": editor 
				},

				{ "sExtends": "editor_remove", 
		            sButtonText: "Obrisi", 
					"editor": editor 
				},

		        {
		            sExtends: "collection",
		            sButtonText: "Sacuvaj",
		            sButtonClass: "save-collection",
		            aButtons: [ 'copy', 'csv', 'xls', 'pdf' ]
		        }
			]
		}
	} );
} );

}(jQuery));

